# Generated by Django 5.0.4 on 2024-05-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_shortimage_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortImage',
            new_name='ShortImages',
        ),
    ]
