# Generated by Django 5.0.4 on 2024-05-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_shortimage_shortimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortimages',
            old_name='short_image',
            new_name='short_images',
        ),
    ]
