# Generated by Django 5.0.4 on 2024-05-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_short_image_shortimages_short_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_featured',
            field=models.BooleanField(default=False),
        ),
    ]
