# Generated by Django 5.0.4 on 2024-05-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='product_wishlist',
        ),
    ]
